global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      # Change from broker:9101 to localhost:9101 for Codespaces
      - targets: ['localhost:9101']

  - job_name: 'stream-metrics'
    static_configs:
      - targets: ['172.17.0.1:8000']  # Using the updated port

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
